export const questions = [
  {
    id: 1,
    question:
      "Es una máquina capaz de procesar y transformar gran cantídad de datos muy rápidamente, de acuerdo con un programa de instrucciones.",
    category: "ofimatica-3RO",
    correct_answer: "Computadora",
    incorrect_answers: ["Calculadora", "Procesador", "Unidad de Procesamiento"],
  },
  {
    id: 2,
    question:
      "Se refiere a las partes físicas, tangibles, de un sistema informático, es decir todo aquello que se puede tocar, sus componentes eléctricos, electrónicos, electromecánicos.",
    category: "ofimatica-3RO",
    correct_answer: "Hardware",
    incorrect_answers: ["Computadora", "Software", "CPU"],
  },
  {
    id: 3,
    question:
      "Conjunto de programas, instrucciones y reglas informáticas que permiten ejecutar distintas tareas en una computadora. Se considera que es el equipamiento lógico e intangible de un ordenador.",
    category: "ofimatica-3RO",
    correct_answer: "Software",
    incorrect_answers: ["Sistema Operativo", "Hardware", "Microsoft Office"],
  },
  {
    id: 4,
    question:
      "Es un conjunto de programas que hacen posible la comunicación entre el usuario y la computadora; esto es la interfaz, todo aquel medio físico que conecta un dispositivo periférico con la computadora; o todo software que comunica al usuario con la computadora.",
    category: "ofimatica-3RO",
    correct_answer: "Sistema Operativo",
    incorrect_answers: ["Software", "Hardware", "Microsoft Office"],
  },
  {
    id: 5,
    question: "¿Qué significan las siglas CPU en español?",
    category: "ofimatica-3RO",
    correct_answer: "Unidad Central de Procesamiento",
    incorrect_answers: [
      "Central de proceso unitario",
      "Centro de procesamiento unificado",
      "Unidad de comunicación de procesos",
    ],
  },
  {
    id: 6,
    question: "¿Qué significan las siglas RAM en español?",
    category: "ofimatica-3RO",
    correct_answer: "Memoria de acceso aleatorio",
    incorrect_answers: [
      "Memoria aleatoria rapida",
      "Memoria de solo lectura",
      "Memoria de acceso rapido",
    ],
  },
  {
    id: 7,
    question: "¿Qué significan las siglas ROM en español?",
    category: "ofimatica-3RO",
    correct_answer: "Memoria de solo lectura",
    incorrect_answers: [
      "Memoria de acceso aleatorio",
      "Memoria oportuna rapida",
      "Memoria de acceso rapido",
    ],
  },
  {
    id: 8,
    question: "Ejemplos de dispositivos o perifericos de entrada?",
    category: "ofimatica-3RO",
    correct_answer: "Teclado, mouse, scanner",
    incorrect_answers: [
      "Monitor, impresora, bocinas",
      "Proyector, camara web, microfono",
      "Memoria USB, disco duro, CD",
    ],
  },
  {
    id: 9,
    question: "Ejemplos de dispositivos o perifericos de salida?",
    category: "ofimatica-3RO",
    correct_answer: "Monitor, impresora, bocinas",
    incorrect_answers: [
      "Teclado, mouse, scanner",
      "Proyector, camara web, microfono",
      "Memoria USB, disco duro, CD",
    ],
  },
  {
    id: 10,
    question: "1 megabyte es igual a:",
    category: "ofimatica-3RO",
    correct_answer: "1024 kilobytes",
    incorrect_answers: ["1024 bytes", "1000 kilobytes", "1000 bytes"],
  },
  {
    id: 11,
    question: "1 byte es igual a:",
    category: "ofimatica-3RO",
    correct_answer: "8 bits",
    incorrect_answers: ["4 bits", "100 bits", "1024 bits"],
  },
  {
    id: 12,
    question: "1 terabyte es igual a:",
    category: "ofimatica-3RO",
    correct_answer: "1024 gigabytes",
    incorrect_answers: ["1024 kilobytes", "1000 bytes", "1000 megabytes"],
  },
  {
    id: 13,
    question: "1 gigabyte es igual a:",
    category: "ofimatica-3RO",
    correct_answer: "1024 megabytes",
    incorrect_answers: ["1024 kilobytes", "1000 bytes", "1000 megabytes"],
  },
  {
    id: 14,
    question: "¿Qué significan las siglas USB en español?",
    category: "ofimatica-3RO",
    correct_answer: "Bus de serie universal",
    incorrect_answers: [
      "Bus de sistema universal",
      "Bus de serie unico",
      "Bus de sistema unico",
    ],
  },
  {
    id: 15,
    question: "Fundador de Meta (Facebook)",
    category: "ofimatica-3RO",
    correct_answer: "Mark Zuckerberg",
    incorrect_answers: ["Bill Gates", "Steve Jobs", "Jeff Bezos"],
  },
  {
    id: 16,
    question: "Fundador de Microsoft",
    category: "ofimatica-3RO",
    correct_answer: "Bill Gates",
    incorrect_answers: ["Steve Jobs", "Mark Zuckerberg", "Jeff Bezos"],
  },
  {
    id: 17,
    question: "Fundador de Apple",
    category: "ofimatica-3RO",
    correct_answer: "Steve Jobs",
    incorrect_answers: ["Bill Gates", "Mark Zuckerberg", "Jeff Bezos"],
  },
  {
    id: 18,
    question: "¿Qué significa la siglas PC en español?",
    category: "ofimatica-3RO",
    correct_answer: "Computadora Personal",
    incorrect_answers: [
      "Computadora Portatil",
      "Computadora de escritorio",
      "Computadora de oficina",
    ],
  },
  {
    id: 19,
    question: "¿Comó se le llama al conjunto de 4 bits?",
    category: "ofimatica-3RO",
    correct_answer: "Nibble",
    incorrect_answers: ["Byte", "Kilobyte", "Megabyte"],
  },
  {
    id: 20,
    question: "Ofimática es un acronimo de:",
    category: "ofimatica-3RO",
    correct_answer: "Oficina e Informática",
    incorrect_answers: [
      "Oficina y Matemáticas",
      "Oficina y Automatica",
      "Oficina e Información",
    ],
  },
  {
    id: 21,
    question: "¿Qué son las herramientas ofimáticas?",
    category: "ofimatica-3RO",
    correct_answer:
      "Conjunto de aplicaciones informáticas que se utilizan en oficinas para mejorar, automatizar y optimizar los procedimientos y tareas",
    incorrect_answers: [
      "Conjunto de aplicaciones informáticas que se utilizan en la creación de graficos",
      "Conjunto de aplicaciones informáticas que se utilizan para el desarrollo de software",
      "Conjunto de aplicaciones informáticas que se utilizan para la herramientas de diseño",
    ],
  },
  {
    id: 22,
    question: "Ejemplos de herramientas ofimáticas:",
    category: "ofimatica-3RO",
    correct_answer: "Word, Excel, Power Point, Access",
    incorrect_answers: [
      "Photoshop, Illustrator, InDesign",
      "Visual Studio, NetBeans, Eclipse",
      "Chrome, Firefox, Edge",
    ],
  },
  {
    id: 23,
    question: "¿Que es un procesador de texto?",
    category: "ofimatica-3RO",
    correct_answer:
      "Es un software que permite la creación, edición e impresión de documentos de texto",
    incorrect_answers: [
      "Es un software que permite la creación, edición e impresión de imagenes",
      "Es un software que permite la creación, edición e impresión de videos",
      "Es un software que permite la creación, edición e impresión de presentaciones",
    ],
  },
  {
    id: 24,
    question: "¿Que es una hoja de cálculo?",
    category: "ofimatica-3RO",
    correct_answer:
      "Programa para la manipulación de datos dispuestos en forma de tablas, con la finalidad de efectuar operaciones complejas con fórmulas y funciones",
    incorrect_answers: [
      "Programa para la creación de presentaciones",
      "Programa para la creación de hojas de estilos",
      "Programa para la creación de graficos",
    ],
  },
  {
    id: 25,
    question: "Ejemplos de procesadores de texto:",
    category: "ofimatica-3RO",
    correct_answer: "Word, Google Docs, LibreOffice Writer",
    incorrect_answers: [
      "Word, LibreOffice Calc, Google Sheets",
      "LibreOffice Impress, Power Point, Google Slides",
      "Google Docs, Power Point, LibreOffice Writer",
    ],
  },
  {
    id: 26,
    question: "Ejemplos de hojas de cálculo:",
    category: "ofimatica-3RO",
    correct_answer: "Excel, Google Sheets, LibreOffice Calc",
    incorrect_answers: [
      "Word, Google Sheets, LibreOffice Writer",
      "LibreOffice calc, Power Point, Google Slides",
      "Google Docs, Power Point, LibreOffice Writer",
    ],
  },
  {
    id: 27,
    question: "Ejemplos de presentadores de diapositivas:",
    category: "ofimatica-3RO",
    correct_answer: "Power Point, Google Slides, LibreOffice Impress",
    incorrect_answers: [
      "Word, Google Sheets, LibreOffice Impress",
      "LibreOffice calc, Power Point, Google Slides",
      "Google Docs, Power Point, LibreOffice Writer",
    ],
  },
  {
    id: 28,
    question:
      "Las aplicaciones: Word, Excel, Power Point, Access, pertenecen a la suite de:",
    category: "ofimatica-3RO",
    correct_answer: "Microsoft Office",
    incorrect_answers: ["Google Suite", "LibreOffice", "Adobe Suite"],
  },
  {
    id: 29,
    question: "Ejemplos de sistemas operativos:",
    category: "ofimatica-3RO",
    correct_answer: "Windows, MacOS, Linux",
    incorrect_answers: [
      "Word, Excel, Power Point, Access",
      "Windows, Chrome, Firefox",
      "Android, iOS, Access",
    ],
  },
  {
    id: 30,
    question: "¿Que es una red de computadoras?",
    category: "ofimatica-3RO",
    correct_answer:
      "Conjunto de computadoras y otros dispositivos interconectados entre sí para compartir información, recursos y servicios",
    incorrect_answers: [
      "Conjunto de computadoras y otros dispositivos conectados entre sí para compartir información",
      "Conjunto de computadoras y otros dispositivos conectados entre sí para compartir recursos",
      "Conjunto de computadoras y otros dispositivos interconectados entre sí para navegar en internet",
    ],
  },
  {
    id: 31,
    question: "¿Qué es una topología de red?",
    category: "ofimatica-3RO",
    correct_answer:
      "Es la forma en que están distribuidos los dispositivos y las conexiones en una red de computadoras",
    incorrect_answers: [
      "Es la protocolo que utilizan los dispositivos para comunicarse entre sí",
      "Es la velocidad de transferencia de datos en una red de computadoras",
      "Es la cantidad de dispositivos conectados en una red de computadoras",
    ],
  },
  {
    id: 32,
    question: "¿Qué topologías de red existen?",
    category: "ofimatica-3RO",
    correct_answer: "Estrella, Anillo, Malla, Bus, Doble Anillo",
    incorrect_answers: [
      "Estrella, Anillo, Malla, Triangular",
      "Estrella, Anillo, Rectangular, Bus",
      "Estrella, Anillo, Malla, Lineal, Bus",
    ],
  },
  {
    id: 33,
    question:
      "Es la topología donde todos los dispositivos están conectados a un punto central, que puede ser un switch o un router:",
    category: "ofimatica-3RO",
    correct_answer: "Estrella",
    incorrect_answers: ["Anillo", "Malla", "Bus"],
  },
  {
    id: 34,
    question:
      "Topología de red donde todos los dispositivos están conectados todos con todos:",
    category: "ofimatica-3RO",
    correct_answer: "Malla",
    incorrect_answers: ["Estrella", "Anillo", "Bus"],
  },
  {
    id: 35,
    question:
      "Topología de red donde todos los dispositivos están conectados en un solo cable:",
    category: "ofimatica-3RO",
    correct_answer: "Bus",
    incorrect_answers: ["Estrella", "Anillo", "Malla"],
  },
  {
    id: 36,
    question:
      "Qué topología de red es la mas utilizada en las redes de computadoras:",
    category: "ofimatica-3RO",
    correct_answer: "Estralla",
    incorrect_answers: ["Anillo", "Malla", "Bus"],
  },
  {
    id: 37,
    question:
      "Topología de red donde los dispositivos están conectados uno tras otro formando un circulo:",
    category: "ofimatica-3RO",
    correct_answer: "Anillo",
    incorrect_answers: ["Estrella", "Malla", "Bus"],
  },
  {
    id: 38,
    question: "¿Qué significan la siglas LAN en español?",
    category: "ofimatica-3RO",
    correct_answer: "Red de área local",
    incorrect_answers: [
      "Red de area nacional",
      "Red de area mundial",
      "Red de area regional",
    ],
  },
  {
    id: 39,
    question: "¿Qué significan la siglas WAN en español?",
    category: "ofimatica-3RO",
    correct_answer: "Red de área amplia",
    incorrect_answers: [
      "Red de area local",
      "Red de area nacional",
      "Red de area mundial",
    ],
  },
  {
    id: 40,
    question: "¿Qué significan las siglas WLAN en español?",
    category: "ofimatica-3RO",
    correct_answer: "Red de área local inalámbrica",
    incorrect_answers: [
      "Red de area local web",
      "Red de area local nacional",
      "Red de area local mundial",
    ],
  },
  {
  id: 41,
  question: "¿Para qué sirve la Papelera de reciclaje de Windows?",
  category: "ofimatica-3RO",
  correct_answer: "Almacenar temporalmente archivos eliminados",
  incorrect_answers: [
    "Guardar copias de seguridad automáticamente",
    "Instalar programas",
    "Organizar las aplicaciones del sistema",
  ],
},
{
  id: 42,
  question: "¿Qué combinación de teclas se utiliza normalmente para copiar un archivo o texto?",
  category: "ofimatica-3RO",
  correct_answer: "Ctrl + C",
  incorrect_answers: [
    "Ctrl + V",
    "Ctrl + X",
    "Ctrl + Z",
  ],
},
{
  id: 43,
  question: "¿Qué combinación de teclas se utiliza para pegar un elemento que previamente fue copiado?",
  category: "ofimatica-3RO",
  correct_answer: "Ctrl + V",
  incorrect_answers: [
    "Ctrl + C",
    "Ctrl + X",
    "Ctrl + Z",
  ],
},
{
  id: 44,
  question: "¿Qué combinación de teclas permite deshacer la última acción realizada?",
  category: "ofimatica-3RO",
  correct_answer: "Ctrl + Z",
  incorrect_answers: [
    "Ctrl + Y",
    "Ctrl + X",
    "Ctrl + A",
  ],
},
{
  id: 45,
  question: "¿Qué herramienta de Windows permite explorar y administrar archivos y carpetas?",
  category: "ofimatica-3RO",
  correct_answer: "Explorador de archivos",
  incorrect_answers: [
    "Administrador de tareas",
    "Panel de control",
    "Microsoft Defender",
  ],
},
{
  id: 46,
  question: "¿Qué sucede normalmente cuando se presiona la tecla F2 sobre un archivo seleccionado en Windows?",
  category: "ofimatica-3RO",
  correct_answer: "Permite cambiar el nombre del archivo",
  incorrect_answers: [
    "Abre el archivo",
    "Elimina el archivo permanentemente",
    "Copia el archivo",
  ],
},
{
  id: 47,
  question: "¿Cuál de las siguientes opciones representa correctamente una extensión de archivo de Microsoft Word?",
  category: "ofimatica-3RO",
  correct_answer: ".docx",
  incorrect_answers: [
    ".xlsx",
    ".pptx",
    ".exe",
  ],
},
{
  id: 48,
  question: "¿Cuál es la extensión de archivo utilizada normalmente por Microsoft Excel?",
  category: "ofimatica-3RO",
  correct_answer: ".xlsx",
  incorrect_answers: [
    ".docx",
    ".pptx",
    ".jpg",
  ],
},
{
  id: 49,
  question: "¿Cuál es la extensión de archivo utilizada normalmente por Microsoft PowerPoint?",
  category: "ofimatica-3RO",
  correct_answer: ".pptx",
  incorrect_answers: [
    ".docx",
    ".xlsx",
    ".txt",
  ],
},
{
  id: 50,
  question: "¿Qué combinación de teclas se utiliza normalmente para seleccionar todo el contenido de un documento?",
  category: "ofimatica-3RO",
  correct_answer: "Ctrl + A",
  incorrect_answers: [
    "Ctrl + S",
    "Ctrl + P",
    "Ctrl + F",
  ],
},
{
  id: 51,
  question: "En Microsoft Word, ¿qué opción permite hacer que un texto aparezca más oscuro y resaltado?",
  category: "ofimatica-3RO",
  correct_answer: "Negrita",
  incorrect_answers: [
    "Cursiva",
    "Subrayado",
    "Justificar",
  ],
},
{
  id: 52,
  question: "En Microsoft Word, ¿qué alineación hace que el texto quede ajustado tanto al margen izquierdo como al derecho?",
  category: "ofimatica-3RO",
  correct_answer: "Justificada",
  incorrect_answers: [
    "Izquierda",
    "Centrada",
    "Derecha",
  ],
},
{
  id: 53,
  question: "¿Para qué sirve la opción 'Guardar como' en un documento de Word?",
  category: "ofimatica-3RO",
  correct_answer: "Guardar una copia con otro nombre, ubicación o formato",
  incorrect_answers: [
    "Cerrar el documento sin guardarlo",
    "Eliminar el documento original",
    "Imprimir automáticamente el documento",
  ],
},
{
  id: 54,
  question: "En Microsoft Excel, ¿cómo se identifica normalmente una celda?",
  category: "ofimatica-3RO",
  correct_answer: "Con una letra y un número, por ejemplo A1",
  incorrect_answers: [
    "Con dos números, por ejemplo 11",
    "Con dos letras, por ejemplo AB",
    "Con el nombre de la hoja únicamente",
  ],
},
{
  id: 55,
  question: "En Excel, ¿con qué símbolo comienza normalmente una fórmula?",
  category: "ofimatica-3RO",
  correct_answer: "=",
  incorrect_answers: [
    "+",
    "#",
    "@",
  ],
},
{
  id: 56,
  question: "¿Qué función de Excel permite sumar los valores de un grupo de celdas?",
  category: "ofimatica-3RO",
  correct_answer: "SUMA",
  incorrect_answers: [
    "PROMEDIO",
    "CONTAR",
    "MAX",
  ],
},
{
  id: 57,
  question: "¿Qué función de Excel permite obtener el promedio de varios valores?",
  category: "ofimatica-3RO",
  correct_answer: "PROMEDIO",
  incorrect_answers: [
    "SUMA",
    "CONTAR",
    "MIN",
  ],
},
{
  id: 58,
  question: "¿Qué representa el rango A1:A5 en Excel?",
  category: "ofimatica-3RO",
  correct_answer: "El conjunto de celdas desde A1 hasta A5",
  incorrect_answers: [
    "Solamente la celda A1",
    "Solamente la celda A5",
    "Las celdas A1 y A5 únicamente",
  ],
},
{
  id: 59,
  question: "¿Qué herramienta de Excel permite organizar datos de menor a mayor o de mayor a menor?",
  category: "ofimatica-3RO",
  correct_answer: "Ordenar",
  incorrect_answers: [
    "Combinar celdas",
    "Formato condicional",
    "Insertar comentario",
  ],
},
{
  id: 60,
  question: "¿Qué elemento de PowerPoint representa cada una de las páginas de una presentación?",
  category: "ofimatica-3RO",
  correct_answer: "Diapositiva",
  incorrect_answers: [
    "Celda",
    "Párrafo",
    "Hoja",
  ],
},
{
  id: 61,
  question: "¿Qué es una transición en PowerPoint?",
  category: "ofimatica-3RO",
  correct_answer: "El efecto que ocurre al pasar de una diapositiva a otra",
  incorrect_answers: [
    "El movimiento de un texto dentro de una diapositiva",
    "El cambio de fuente de un texto",
    "La corrección ortográfica de una presentación",
  ],
},
{
  id: 62,
  question: "¿Qué es una animación en PowerPoint?",
  category: "ofimatica-3RO",
  correct_answer: "Un efecto aplicado a un objeto dentro de una diapositiva",
  incorrect_answers: [
    "Un efecto entre dos diapositivas",
    "Una herramienta para guardar la presentación",
    "Una opción para imprimir diapositivas",
  ],
},
{
  id: 63,
  question: "¿Cuál es la principal diferencia entre una transición y una animación en PowerPoint?",
  category: "ofimatica-3RO",
  correct_answer: "La transición ocurre entre diapositivas y la animación sobre objetos de una diapositiva",
  incorrect_answers: [
    "La transición solo funciona con imágenes y la animación solo con texto",
    "Son exactamente lo mismo",
    "La animación ocurre entre diapositivas y la transición sobre objetos",
  ],
},
{
  id: 64,
  question: "¿Qué tecla permite iniciar una presentación de PowerPoint desde el principio?",
  category: "ofimatica-3RO",
  correct_answer: "F5",
  incorrect_answers: [
    "F1",
    "F2",
    "F12",
  ],
},
{
  id: 65,
  question: "¿Qué es un algoritmo?",
  category: "ofimatica-3RO",
  correct_answer: "Conjunto de pasos ordenados para resolver un problema",
  incorrect_answers: [
    "Un programa informático escrito exclusivamente en un lenguaje de alto nivel para ser ejecutado en la nube.",
    "Una representación gráfica que sirve únicamente para almacenar variables y datos numéricos en la memoria RAM",
    "Un dispositivo físico de almacenamiento secundario que traduce código binario a señales eléctricas.",
  ],
},
{
  id: 66,
  question: "¿Qué herramienta permite guardar un archivo en la nube de Microsoft?",
  category: "ofimatica-3RO",
  correct_answer: "OneDrive",
  incorrect_answers: ["Dropbox", "iCloud", "Google Drive"],
},
{
  id: 67,
  question: "¿Qué programa se usa para navegar en Internet?",
  category: "ofimatica-3RO",
  correct_answer: "Navegador",
  incorrect_answers: ["Microsoft Word", "Microsoft Excel", "Paint"],
},
{
  id: 68,
  question: "¿Cuáles son las tres características principales de un algoritmo?",
  category: "ofimatica-3RO",
  correct_answer: "Finito, Preciso, Inicio y fin",
  incorrect_answers: ["Preciso, Infinito, Inicio", "Infinito, Ambiguo, Fin", "Inicio, Fin, Finito"],
},
{
  id: 69,
  question: "Es la represntación gráfica de un algoritmo.",
  category: "ofimatica-3RO",
  correct_answer: "Diagamra de flujo",
  incorrect_answers: ["Mapa Conceptual", "Diagrama de estados", "Gráfica de un algoritmo"],
},
{
  id: 70,
  question: "En un algoritmo, ¿qué es una variable?",
  category: "ofimatica-3RO",
  correct_answer: "Un espacio donde se almacena un dato que puede cambiar durante la ejecución del algoritmo",
  incorrect_answers: [
    "Una instrucción que siempre se ejecuta de la misma manera",
    "Un dispositivo físico que permite ejecutar el algoritmo",
    "Un conjunto de pasos que se utilizan para resolver un problema",
  ],
},
{
  id: 71,
  question: "En un algoritmo, ¿cuál de los siguientes es un operador matemático?",
  category: "ofimatica-3RO",
  correct_answer: "+",
  incorrect_answers: [
    "=",
    "&&",
    "==",
  ],
},
{
  id: 72,
  question: "¿Qué operación realiza el operador % en un algoritmo?",
  category: "ofimatica-3RO",
  correct_answer: "Obtiene el residuo de una división",
  incorrect_answers: [
    "Realiza una suma",
    "Realiza una multiplicación",
    "Compara dos valores",
  ],
},
{
  id: 73,
  question: "En un algoritmo, ¿qué significa normalmente el operador de asignación =?",
  category: "ofimatica-3RO",
  correct_answer: "Asignar un valor a una variable",
  incorrect_answers: [
    "Comparar dos valores",
    "Realizar una suma",
    "Indicar que dos valores son diferentes",
  ],
},
{
  id: 74,
  question: "Si en un algoritmo encontramos la instrucción edad = 14, ¿qué significa?",
  category: "ofimatica-3RO",
  correct_answer: "Asignar el valor 14 a la variable edad",
  incorrect_answers: [
    "Comparar edad con el número 14",
    "Sumar 14 a la variable edad",
    "Comprobar si edad es diferente de 14",
  ],
},
{
  id: 75,
  question: "¿Para qué se utilizan principalmente los operadores lógicos en un algoritmo?",
  category: "ofimatica-3RO",
  correct_answer: "Para combinar o evaluar condiciones",
  incorrect_answers: [
    "Para almacenar información en una variable",
    "Para realizar únicamente operaciones matemáticas",
    "Para cambiar el nombre de un archivo",
  ],
},
{
  id: 76,
  question: "¿Cuál de los siguientes es un operador lógico?",
  category: "ofimatica-3RO",
  correct_answer: "&&",
  incorrect_answers: [
    "+",
    "=",
    "%",
  ],
},
{
  id: 77,
  question: "¿Cuál de los siguientes es el operador lógico Y (AND)",
  category: "ofimatica-3RO",
  correct_answer: "&&",
  incorrect_answers: [
    "!=",
    "==",
    "||",
  ],
},
{
  id: 78,
  question: "¿Cuál de los siguientes es el operador lógico O (OR)",
  category: "ofimatica-3RO",
  correct_answer: "&&",
  incorrect_answers: [
    "!=",
    "==",
    "||",
  ],
},
{
  id: 79,
question: "Observa la expresión: edad == 15. ¿Qué está haciendo el algoritmo",
  category: "ofimatica-3RO",
  correct_answer: "Comprobando si edad es igual a 15",
  incorrect_answers: [
    "Comprobando si edad es mayor o igual a 15",
    "Asignado 15 a la variable edad",
    "Comprobando si edad es menor o igual a 15",
  ],
},
{
  id: 80,
  question: "Observa la expresión: edad >= 12. ¿Qué está haciendo el algoritmo?",
  category: "ofimatica-3RO",
  correct_answer: "Comprobando si edad es mayor o igual a 12",
  incorrect_answers: [
    "Asignando 12 a la variable edad",
    "Sumando 12 a la variable edad",
    "Comprobando si edad es menor que 12",
  ],
},
];